In [1]:
import schnet_v1
from importlib import reload
import numpy as np
import torch
import time

In [13]:
a = np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a[]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [72]:
reload(schnet_v1)

<module 'schnet_v1' from '/pool/radekc/GROMOS/GROMOS_workstation/gromosXX/md++/src/interaction/qmmm/schnet_v1.py'>

In [81]:
mlp_calculator = schnet_v1.Pert_SchNet_V1_Calculator('/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/PM7/best_model', ['/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/PM7_val/best_model', '/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/B3LYP_DZ/best_model'], 100, 100, 0, [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]) # '/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/B3LYP_DZ/best_model'

In [15]:
mlp_calculator.get_state(atomic_numbers=[6, 8, 1, 1, 1, 1, 6, 1, 1, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1,
        8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1,
        8, 1, 1], positions=[[ 3.7975e-01,  2.9263e-01,  1.9135e-01],
        [-1.0409e+00,  3.7623e-01,  4.9951e-02],
        [ 7.9817e-01, -3.7328e-01, -5.7777e-01],
        [ 6.1009e-01, -1.5569e-01,  1.1691e+00],
        [ 9.3262e-01,  1.2397e+00,  1.0529e-01],
        [-1.5564e+00, -9.9104e-04,  8.1935e-01],
        [ 3.7975e-01,  2.9263e-01,  1.9135e-01],
        [-1.0409e+00,  3.7623e-01,  4.9951e-02],
        [ 7.9817e-01, -3.7328e-01, -5.7777e-01],
        [ 6.1009e-01, -1.5569e-01,  1.1691e+00],
        [ 9.3262e-01,  1.2397e+00,  1.0529e-01],
        [-2.4124e+00, -3.7555e+00,  8.9283e-01],
        [-2.8495e+00, -4.6466e+00,  1.0158e+00],
        [-1.7852e+00, -3.5845e+00,  1.6527e+00],
        [ 6.8420e-01,  4.0696e+00,  1.4046e+00],
        [ 1.2111e+00,  4.8352e+00,  1.7739e+00],
        [ 3.4471e-01,  4.3071e+00,  4.9438e-01],
        [-1.5048e+00,  6.1030e-01, -4.4482e+00],
        [-2.2833e+00,  5.8166e-01, -5.0754e+00],
        [-7.2098e-01,  1.0268e+00, -4.9091e+00],
        [ 3.4947e+00,  6.3116e-04, -1.2378e+00],
        [ 3.3576e+00, -7.0224e-01, -1.9358e+00],
        [ 3.9314e+00, -4.0704e-01, -4.3586e-01],
        [-2.1886e+00, -1.0438e+00, -2.2044e+00],
        [-1.9488e+00, -5.8731e-01, -1.3475e+00],
        [-1.6751e+00, -6.3111e-01, -2.9568e+00],
        [ 1.5148e+00, -2.5455e+00,  2.4992e+00],
        [ 1.5898e+00, -3.3271e+00,  1.8799e+00],
        [ 2.2134e+00, -1.8685e+00,  2.2674e+00],
        [-1.3390e+00,  3.2696e+00,  3.5298e+00],
        [-2.2351e+00,  2.8373e+00,  3.4282e+00],
        [-1.1681e+00,  3.8697e+00,  2.7482e+00],
        [-9.5115e-01, -2.9725e+00,  3.2980e+00],
        [-9.7445e-01, -3.2824e+00,  4.2485e+00],
        [-2.6868e-03, -2.8173e+00,  3.0213e+00],
        [-3.9358e-01,  4.5757e+00, -9.3320e-01],
        [-6.1830e-01,  5.2537e+00, -1.6332e+00],
        [-5.8407e-01,  3.6588e+00, -1.2841e+00],
        [-3.7149e-01,  1.9625e+00, -2.2576e+00],
        [-8.2992e-01,  1.4843e+00, -3.0069e+00],
        [-6.8592e-01,  1.5914e+00, -1.3838e+00],
        [ 2.9727e+00,  2.7891e+00,  4.9363e-01],
        [ 2.7449e+00,  1.9886e+00, -6.0836e-02],
        [ 2.1976e+00,  3.0178e+00,  1.0828e+00],
        [-2.4039e+00, -7.5181e-01,  2.0396e+00],
        [-3.3045e+00, -1.1113e+00,  1.7949e+00],
        [-1.9344e+00, -1.4055e+00,  2.6332e+00],
        [ 3.6126e+00, -1.0317e+00,  1.4521e+00],
        [ 4.1282e+00, -1.8713e+00,  1.2809e+00],
        [ 4.0579e+00, -5.0971e-01,  2.1796e+00],
        [ 5.1799e-01, -2.2947e+00, -3.8422e+00],
        [-1.2582e-01, -2.2907e+00, -4.6075e+00],
        [ 1.2056e-01, -2.7985e+00, -3.0751e+00],
        [-5.6065e-01, -3.3084e+00, -9.0193e-01],
        [-1.1274e-01, -2.5905e+00, -3.6894e-01],
        [-1.5023e+00, -3.4207e+00, -5.8436e-01]], state_id=2)

KeyError: 2

In [82]:
# two states dual topo
start= time.time()
mlp_calculator.calculate_next_step(atomic_numbers=[6, 8, 1, 1, 1, 1, 6, 1, 1, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1,
        8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1,
        8, 1, 1], positions=[[ 3.7975e-01,  2.9263e-01,  1.9135e-01],
        [-1.0409e+00,  3.7623e-01,  4.9951e-02],
        [ 7.9817e-01, -3.7328e-01, -5.7777e-01],
        [ 6.1009e-01, -1.5569e-01,  1.1691e+00],
        [ 9.3262e-01,  1.2397e+00,  1.0529e-01],
        [-1.5564e+00, -9.9104e-04,  8.1935e-01],
        [ 3.7975e-01,  2.9263e-01,  1.9135e-01],
        [-1.0409e+00,  3.7623e-01,  4.9951e-02],
        [ 7.9817e-01, -3.7328e-01, -5.7777e-01],
        [ 6.1009e-01, -1.5569e-01,  1.1691e+00],
        [ 9.3262e-01,  1.2397e+00,  1.0529e-01],
        [-2.4124e+00, -3.7555e+00,  8.9283e-01],
        [-2.8495e+00, -4.6466e+00,  1.0158e+00],
        [-1.7852e+00, -3.5845e+00,  1.6527e+00],
        [ 6.8420e-01,  4.0696e+00,  1.4046e+00],
        [ 1.2111e+00,  4.8352e+00,  1.7739e+00],
        [ 3.4471e-01,  4.3071e+00,  4.9438e-01],
        [-1.5048e+00,  6.1030e-01, -4.4482e+00],
        [-2.2833e+00,  5.8166e-01, -5.0754e+00],
        [-7.2098e-01,  1.0268e+00, -4.9091e+00],
        [ 3.4947e+00,  6.3116e-04, -1.2378e+00],
        [ 3.3576e+00, -7.0224e-01, -1.9358e+00],
        [ 3.9314e+00, -4.0704e-01, -4.3586e-01],
        [-2.1886e+00, -1.0438e+00, -2.2044e+00],
        [-1.9488e+00, -5.8731e-01, -1.3475e+00],
        [-1.6751e+00, -6.3111e-01, -2.9568e+00],
        [ 1.5148e+00, -2.5455e+00,  2.4992e+00],
        [ 1.5898e+00, -3.3271e+00,  1.8799e+00],
        [ 2.2134e+00, -1.8685e+00,  2.2674e+00],
        [-1.3390e+00,  3.2696e+00,  3.5298e+00],
        [-2.2351e+00,  2.8373e+00,  3.4282e+00],
        [-1.1681e+00,  3.8697e+00,  2.7482e+00],
        [-9.5115e-01, -2.9725e+00,  3.2980e+00],
        [-9.7445e-01, -3.2824e+00,  4.2485e+00],
        [-2.6868e-03, -2.8173e+00,  3.0213e+00],
        [-3.9358e-01,  4.5757e+00, -9.3320e-01],
        [-6.1830e-01,  5.2537e+00, -1.6332e+00],
        [-5.8407e-01,  3.6588e+00, -1.2841e+00],
        [-3.7149e-01,  1.9625e+00, -2.2576e+00],
        [-8.2992e-01,  1.4843e+00, -3.0069e+00],
        [-6.8592e-01,  1.5914e+00, -1.3838e+00],
        [ 2.9727e+00,  2.7891e+00,  4.9363e-01],
        [ 2.7449e+00,  1.9886e+00, -6.0836e-02],
        [ 2.1976e+00,  3.0178e+00,  1.0828e+00],
        [-2.4039e+00, -7.5181e-01,  2.0396e+00],
        [-3.3045e+00, -1.1113e+00,  1.7949e+00],
        [-1.9344e+00, -1.4055e+00,  2.6332e+00],
        [ 3.6126e+00, -1.0317e+00,  1.4521e+00],
        [ 4.1282e+00, -1.8713e+00,  1.2809e+00],
        [ 4.0579e+00, -5.0971e-01,  2.1796e+00],
        [ 5.1799e-01, -2.2947e+00, -3.8422e+00],
        [-1.2582e-01, -2.2907e+00, -4.6075e+00],
        [ 1.2056e-01, -2.7985e+00, -3.0751e+00],
        [-5.6065e-01, -3.3084e+00, -9.0193e-01],
        [-1.1274e-01, -2.5905e+00, -3.6894e-01],
        [-1.5023e+00, -3.4207e+00, -5.8436e-01]], time_step=0)
end = time.time()
print(end - start)

1.7016549534322014 0.2763049697100036
1.7016549534322014
0.12697935104370117


In [63]:
[[ 7.74345398e-02  2.58567734e+01 -1.91423206e+01]
 [-1.99016991e+01 -1.11471539e+01  1.58177357e+01]
 [ 9.42019081e+00 -8.69546294e-01  4.84596109e+00]
 [-7.60465622e-01 -3.69212198e+00 -6.20621681e-01]
 [ 1.99070168e+01 -5.75167561e+00  3.35352838e-01]
 [-1.24051800e+01 -2.21196842e+00  1.00615156e+00]
 [ 2.94357796e+01  6.87127495e+00  2.89416742e+00]
 [-7.44629288e+01  9.45926785e-01 -6.33255100e+00]
 [ 1.46233740e+01 -4.52500534e+00 -3.36722898e+00]
 [ 1.14176750e+01 -6.06697941e+00  7.87058449e+00]
 [ 1.89861012e+01  2.77478600e+00 -1.06497002e+00]
 [-6.94413424e-01 -1.56489491e+00 -2.04061651e+00]
 [ 1.82351977e-01  6.36976182e-01  2.83828795e-01]
 [ 3.21575671e-01  1.12650597e+00  1.03899693e+00]
 [-2.00822163e+00 -2.01879442e-03 -1.42324817e+00]
 [ 5.63616574e-01  2.19011873e-01  1.78742245e-01]
 [ 1.35106575e+00  2.38891959e-01  1.53476405e+00]
 [ 3.87815833e-02  8.83186579e-01  1.23772013e+00]
 [-4.53715175e-01 -2.27094278e-01 -1.57678574e-01]
 [ 6.13952994e-01 -2.28418916e-01 -8.57283175e-01]
 [ 1.06783915e+00  5.94589591e-01 -1.90166390e+00]
 [-4.99084815e-02 -1.18194208e-01  9.17041421e-01]
 [-7.06926107e-01 -1.79584950e-01  6.93209410e-01]
 [ 1.82709861e+00  2.81693840e+00  5.03023958e+00]
 [-5.01186752e+00 -4.57026386e+00 -2.45845652e+00]
 [ 1.05710471e+00  4.15086746e-04 -2.37594390e+00]
 [ 5.24484217e-01 -1.77326441e+00  5.80754519e-01]
 [-4.16313559e-02  8.05604339e-01  1.27619505e-03]
 [-7.77708352e-01  6.56170130e-01 -4.38723505e-01]
 [ 1.34399131e-01  1.04362500e+00 -6.33160710e-01]
 [-2.08203614e-01 -6.33922100e-01  2.62640923e-01]
 [-1.07680701e-01 -1.78369790e-01  7.23111212e-01]
 [-8.45529661e-02 -2.51713300e+00  8.06673706e-01]
 [ 2.81407952e-01  3.54308963e-01 -2.09966570e-01]
 [-2.14371458e-02  7.93903947e-01  8.06008875e-02]
 [-7.08950520e-01 -2.45889449e+00  4.00538743e-02]
 [-1.59287453e-03  8.50527406e-01 -3.87888759e-01]
 [ 5.67383766e-01  3.09883666e+00 -2.98655808e-01]
 [-9.42401171e-01 -2.57941103e+00  5.79667616e+00]
 [-1.03697443e+00 -1.08235228e+00 -3.17753696e+00]
 [ 4.72245598e+00  8.12351704e-01 -6.52590156e-01]
 [-7.07755089e-01  7.81403363e-01 -8.12140167e-01]
 [-3.16979200e-01 -4.63254690e-01  1.11372590e+00]
 [ 8.98571849e-01 -1.19367290e+00 -1.77728027e-01]
 [ 3.02856469e+00  1.25984311e+00 -8.07821655e+00]
 [ 2.37147474e+00 -4.58102912e-01  3.49960184e+00]
 [-2.93546438e+00  1.67489684e+00 -7.28587389e-01]
 [ 1.04724228e+00 -2.27054656e-02 -4.61322218e-01]
 [-4.31557894e-02  1.98652208e-01  4.48779285e-01]
 [-1.73889697e-01 -1.74156755e-01  1.41067505e-02]
 [-1.24926376e+00  1.32330489e+00  2.73718148e-01]
 [ 3.89480531e-01 -4.71099913e-01 -2.84544110e-01]
 [ 6.81312263e-01 -9.60384488e-01  7.68199563e-03]
 [-1.39912391e+00  2.09463930e+00 -1.72941482e+00]
 [ 1.56026995e+00 -1.89500141e+00  1.37676191e+00]
 [ 1.14090890e-01 -6.96698606e-01  1.10239780e+00]]

SyntaxError: invalid syntax (<ipython-input-63-09527ae60721>, line 1)

In [83]:
# one state
mlp_calculator_one_state = schnet_v1.Pert_SchNet_V1_Calculator('/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/PM7/best_model', ['/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/PM7_val/best_model', '/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/B3LYP_DZ/best_model'], 100, 100, 0, [1, 1, 1, 1, 1, 1]) # '/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/B3LYP_DZ/best_model'

In [85]:
# one state
mlp_calculator_one_state.calculate_next_step(atomic_numbers=[6, 8, 1, 1, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1,
        8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1,
        8, 1, 1], positions=[[ 3.7975e-01,  2.9263e-01,  1.9135e-01],
        [-1.0409e+00,  3.7623e-01,  4.9951e-02],
        [ 7.9817e-01, -3.7328e-01, -5.7777e-01],
        [ 6.1009e-01, -1.5569e-01,  1.1691e+00],
        [ 9.3262e-01,  1.2397e+00,  1.0529e-01],
        [-1.5564e+00, -9.9104e-04,  8.1935e-01],
        [-2.4124e+00, -3.7555e+00,  8.9283e-01],
        [-2.8495e+00, -4.6466e+00,  1.0158e+00],
        [-1.7852e+00, -3.5845e+00,  1.6527e+00],
        [ 6.8420e-01,  4.0696e+00,  1.4046e+00],
        [ 1.2111e+00,  4.8352e+00,  1.7739e+00],
        [ 3.4471e-01,  4.3071e+00,  4.9438e-01],
        [-1.5048e+00,  6.1030e-01, -4.4482e+00],
        [-2.2833e+00,  5.8166e-01, -5.0754e+00],
        [-7.2098e-01,  1.0268e+00, -4.9091e+00],
        [ 3.4947e+00,  6.3116e-04, -1.2378e+00],
        [ 3.3576e+00, -7.0224e-01, -1.9358e+00],
        [ 3.9314e+00, -4.0704e-01, -4.3586e-01],
        [-2.1886e+00, -1.0438e+00, -2.2044e+00],
        [-1.9488e+00, -5.8731e-01, -1.3475e+00],
        [-1.6751e+00, -6.3111e-01, -2.9568e+00],
        [ 1.5148e+00, -2.5455e+00,  2.4992e+00],
        [ 1.5898e+00, -3.3271e+00,  1.8799e+00],
        [ 2.2134e+00, -1.8685e+00,  2.2674e+00],
        [-1.3390e+00,  3.2696e+00,  3.5298e+00],
        [-2.2351e+00,  2.8373e+00,  3.4282e+00],
        [-1.1681e+00,  3.8697e+00,  2.7482e+00],
        [-9.5115e-01, -2.9725e+00,  3.2980e+00],
        [-9.7445e-01, -3.2824e+00,  4.2485e+00],
        [-2.6868e-03, -2.8173e+00,  3.0213e+00],
        [-3.9358e-01,  4.5757e+00, -9.3320e-01],
        [-6.1830e-01,  5.2537e+00, -1.6332e+00],
        [-5.8407e-01,  3.6588e+00, -1.2841e+00],
        [-3.7149e-01,  1.9625e+00, -2.2576e+00],
        [-8.2992e-01,  1.4843e+00, -3.0069e+00],
        [-6.8592e-01,  1.5914e+00, -1.3838e+00],
        [ 2.9727e+00,  2.7891e+00,  4.9363e-01],
        [ 2.7449e+00,  1.9886e+00, -6.0836e-02],
        [ 2.1976e+00,  3.0178e+00,  1.0828e+00],
        [-2.4039e+00, -7.5181e-01,  2.0396e+00],
        [-3.3045e+00, -1.1113e+00,  1.7949e+00],
        [-1.9344e+00, -1.4055e+00,  2.6332e+00],
        [ 3.6126e+00, -1.0317e+00,  1.4521e+00],
        [ 4.1282e+00, -1.8713e+00,  1.2809e+00],
        [ 4.0579e+00, -5.0971e-01,  2.1796e+00],
        [ 5.1799e-01, -2.2947e+00, -3.8422e+00],
        [-1.2582e-01, -2.2907e+00, -4.6075e+00],
        [ 1.2056e-01, -2.7985e+00, -3.0751e+00],
        [-5.6065e-01, -3.3084e+00, -9.0193e-01],
        [-1.1274e-01, -2.5905e+00, -3.6894e-01],
        [-1.5023e+00, -3.4207e+00, -5.8436e-01]], time_step=0)

1.7016549534322014
1.7016549534322014


In [79]:
# two states single topo
mlp_calculator_single_topo = schnet_v1.Pert_SchNet_V1_Calculator('/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/PM7/best_model', ['/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/PM7_val/best_model', '/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/B3LYP_DZ/best_model'], 100, 100, 0, [0, 0, 0, 0, 1, 1, 2]) # '/pool/radekc/CD_lab_project/BuRNN/manuscript_data/MLPs/B3LYP_DZ/best_model'

In [80]:
# two states single topo
start= time.time()
mlp_calculator_single_topo.calculate_next_step(atomic_numbers=[6, 1, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1,
        8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1,
        8, 1, 1], positions=[[ 3.7975e-01,  2.9263e-01,  1.9135e-01],
        [ 7.9817e-01, -3.7328e-01, -5.7777e-01],
        [ 6.1009e-01, -1.5569e-01,  1.1691e+00],
        [ 9.3262e-01,  1.2397e+00,  1.0529e-01],
        [-1.0409e+00,  3.7623e-01,  4.9951e-02],
        [-1.5564e+00, -9.9104e-04,  8.1935e-01],
        [-1.0409e+00,  3.7623e-01,  4.9951e-02],
        [-2.4124e+00, -3.7555e+00,  8.9283e-01],
        [-2.8495e+00, -4.6466e+00,  1.0158e+00],
        [-1.7852e+00, -3.5845e+00,  1.6527e+00],
        [ 6.8420e-01,  4.0696e+00,  1.4046e+00],
        [ 1.2111e+00,  4.8352e+00,  1.7739e+00],
        [ 3.4471e-01,  4.3071e+00,  4.9438e-01],
        [-1.5048e+00,  6.1030e-01, -4.4482e+00],
        [-2.2833e+00,  5.8166e-01, -5.0754e+00],
        [-7.2098e-01,  1.0268e+00, -4.9091e+00],
        [ 3.4947e+00,  6.3116e-04, -1.2378e+00],
        [ 3.3576e+00, -7.0224e-01, -1.9358e+00],
        [ 3.9314e+00, -4.0704e-01, -4.3586e-01],
        [-2.1886e+00, -1.0438e+00, -2.2044e+00],
        [-1.9488e+00, -5.8731e-01, -1.3475e+00],
        [-1.6751e+00, -6.3111e-01, -2.9568e+00],
        [ 1.5148e+00, -2.5455e+00,  2.4992e+00],
        [ 1.5898e+00, -3.3271e+00,  1.8799e+00],
        [ 2.2134e+00, -1.8685e+00,  2.2674e+00],
        [-1.3390e+00,  3.2696e+00,  3.5298e+00],
        [-2.2351e+00,  2.8373e+00,  3.4282e+00],
        [-1.1681e+00,  3.8697e+00,  2.7482e+00],
        [-9.5115e-01, -2.9725e+00,  3.2980e+00],
        [-9.7445e-01, -3.2824e+00,  4.2485e+00],
        [-2.6868e-03, -2.8173e+00,  3.0213e+00],
        [-3.9358e-01,  4.5757e+00, -9.3320e-01],
        [-6.1830e-01,  5.2537e+00, -1.6332e+00],
        [-5.8407e-01,  3.6588e+00, -1.2841e+00],
        [-3.7149e-01,  1.9625e+00, -2.2576e+00],
        [-8.2992e-01,  1.4843e+00, -3.0069e+00],
        [-6.8592e-01,  1.5914e+00, -1.3838e+00],
        [ 2.9727e+00,  2.7891e+00,  4.9363e-01],
        [ 2.7449e+00,  1.9886e+00, -6.0836e-02],
        [ 2.1976e+00,  3.0178e+00,  1.0828e+00],
        [-2.4039e+00, -7.5181e-01,  2.0396e+00],
        [-3.3045e+00, -1.1113e+00,  1.7949e+00],
        [-1.9344e+00, -1.4055e+00,  2.6332e+00],
        [ 3.6126e+00, -1.0317e+00,  1.4521e+00],
        [ 4.1282e+00, -1.8713e+00,  1.2809e+00],
        [ 4.0579e+00, -5.0971e-01,  2.1796e+00],
        [ 5.1799e-01, -2.2947e+00, -3.8422e+00],
        [-1.2582e-01, -2.2907e+00, -4.6075e+00],
        [ 1.2056e-01, -2.7985e+00, -3.0751e+00],
        [-5.6065e-01, -3.3084e+00, -9.0193e-01],
        [-1.1274e-01, -2.5905e+00, -3.6894e-01],
        [-1.5023e+00, -3.4207e+00, -5.8436e-01]], time_step=0)
end = time.time()
print(end-start)

1.701651637112971 0.2763041078606976
1.701651637112971
0.10069108009338379


In [15]:
[[ 2.95131893e+01  3.27280617e+01 -1.62481594e+01]
 [ 2.40435638e+01 -5.39455700e+00  1.47873068e+00]
 [ 1.06572132e+01 -9.75910759e+00  7.24997091e+00]
 [ 3.88931198e+01 -2.97688460e+00 -7.29614854e-01]
 [-1.99017105e+01 -1.11471586e+01  1.58177404e+01]
 [-1.24051771e+01 -2.21196604e+00  1.00614762e+00]
 [-7.44629059e+01  9.45925474e-01 -6.33255005e+00]
 [-6.94413304e-01 -1.56489515e+00 -2.04061699e+00]
 [ 1.82352155e-01  6.36976480e-01  2.83828586e-01]
 [ 3.21575761e-01  1.12650585e+00  1.03899693e+00]
 [-2.00822091e+00 -2.01813877e-03 -1.42324805e+00]
 [ 5.63616812e-01  2.19012097e-01  1.78742439e-01]
 [ 1.35106564e+00  2.38891870e-01  1.53476381e+00]
 [ 3.87812704e-02  8.83186400e-01  1.23772097e+00]
 [-4.53715086e-01 -2.27094352e-01 -1.57678574e-01]
 [ 6.13953412e-01 -2.28418648e-01 -8.57283354e-01]
 [ 1.06783962e+00  5.94589353e-01 -1.90166438e+00]
 [-4.99089211e-02 -1.18194208e-01  9.17041421e-01]
 [-7.06925988e-01 -1.79584742e-01  6.93209052e-01]
 [ 1.82709789e+00  2.81693697e+00  5.03024054e+00]
 [-5.01186800e+00 -4.57026291e+00 -2.45845556e+00]
 [ 1.05710471e+00  4.15265560e-04 -2.37594414e+00]
 [ 5.24483681e-01 -1.77326488e+00  5.80754757e-01]
 [-4.16311324e-02  8.05603862e-01  1.27643347e-03]
 [-7.77709186e-01  6.56170726e-01 -4.38723803e-01]
 [ 1.34398833e-01  1.04362440e+00 -6.33161008e-01]
 [-2.08203495e-01 -6.33921802e-01  2.62640923e-01]
 [-1.07680671e-01 -1.78369850e-01  7.23110676e-01]
 [-8.45528245e-02 -2.51713276e+00  8.06673646e-01]
 [ 2.81407952e-01  3.54308963e-01 -2.09966362e-01]
 [-2.14369968e-02  7.93903947e-01  8.06007683e-02]
 [-7.08950460e-01 -2.45889306e+00  4.00538445e-02]
 [-1.59289688e-03  8.50526452e-01 -3.87888402e-01]
 [ 5.67384243e-01  3.09883642e+00 -2.98655748e-01]
 [-9.42399621e-01 -2.57941008e+00  5.79667568e+00]
 [-1.03697491e+00 -1.08235312e+00 -3.17753792e+00]
 [ 4.72245646e+00  8.12351584e-01 -6.52588964e-01]
 [-7.07754016e-01  7.81404257e-01 -8.12140107e-01]
 [-3.16978931e-01 -4.63254929e-01  1.11372590e+00]
 [ 8.98572147e-01 -1.19367278e+00 -1.77728325e-01]
 [ 3.02856469e+00  1.25984311e+00 -8.07821655e+00]
 [ 2.37147474e+00 -4.58102494e-01  3.49960160e+00]
 [-2.93546367e+00  1.67489684e+00 -7.28587985e-01]
 [ 1.04724205e+00 -2.27055550e-02 -4.61322010e-01]
 [-4.31563258e-02  1.98652744e-01  4.48778927e-01]
 [-1.73889458e-01 -1.74156547e-01  1.41065717e-02]
 [-1.24926376e+00  1.32330441e+00  2.73717582e-01]
 [ 3.89480710e-01 -4.71099854e-01 -2.84544349e-01]
 [ 6.81312382e-01 -9.60384190e-01  7.68187642e-03]
 [-1.39912426e+00  2.09463954e+00 -1.72941458e+00]
 [ 1.56026971e+00 -1.89500153e+00  1.37676179e+00]
 [ 1.14091158e-01 -6.96698189e-01  1.10239756e+00]]

-16.79120445251465

In [6]:
nn_valid_dev

1.7016549534322014